v0.4.0 release
swift-server/vscode-swift pull request #194
Opened 2022-03-14 17:11 UTC by adam-fowler

2022-03-14 17:21 UTC, 0xTim approved these changes

2022-03-14 17:41 UTC, stevapple requested changes
LGTM except for this small typo

2022-03-15 08:01 UTC, stevapple approved these changes

2022-03-15 08:02 UTC, adam-fowler commented
Going to add something to the readme about the test explorer before merging this

2022-03-15 16:31 UTC, merged