[DO NOT MERGE] Add integration tests for TestExplorer
swift-server/vscode-swift pull request #806
Opened 2024-05-17 12:40 UTC by plemarquand

Add some integration tests that exercise finding and running tests, ensuring they complete with the expected outcome.

This patch adds a new profile used when running the tests locally via the Extension Tests task. This ensures that the workspace is always in a clean and consistent state.

2024-05-21 17:39 UTC, plemarquand commented
@swift-server-bot Test this please

2024-05-21 17:40 UTC, plemarquand commented
@swift-server-bot Please test

2024-05-21 18:05 UTC, plemarquand commented
@swift-server-bot Please test

2024-05-21 18:08 UTC, plemarquand commented
@swift-server-bot Test this please

2024-05-22 17:28 UTC, plemarquand commented
@swift-server-bot Test this please

2024-05-25 10:02 UTC, adam-fowler requested changes
For some reason the extension fails to load CodeLLDB when running tests. I get the error 
```
Error: Cannot activate the 'Swift' extension because it depends on unknown extension 'vadimcn.vscode-lldb'
```
Which then causes the TestDiscovery tests to hang.
If I run without the profile everything works

2024-05-25 11:23 UTC, plemarquand commented on .vscode/testing-debug.code-profile
When you create a new profile these are what you get by default.

2024-05-25 12:28 UTC, plemarquand commented
@adam-fowler I'm not sure why the CodeLLDB extension isn't present for you in the profile; the [.code-profile](https://github.com/swift-server/vscode-swift/pull/806/files#diff-3cdf9d533acf8ec324a2acec8acc09a5158e1532b463885603bab8c13faa690cR3) includes it. Do you have it installed in your regular VSCode/profile? I think inclusion in the .code-profile just enables it, but wont install it if it isn't present.

This is what I have in the extensions view in the test code profile:

<img width="1136" alt="Screenshot 2024-05-25 at 8 24 59 AM" src="https://github.com/swift-server/vscode-swift/assets/667875/b677f64f-b357-46ba-a80d-6e5e67f00aa4">

2024-05-26 10:47 UTC, adam-fowler commented
Worked out what the issue is. I didn't realise I have to import the profile before using it.
Currently I'm seeing a number of tests fail when running with Swift 5.10

2024-05-26 13:02 UTC, plemarquand commented
@adam-fowler Which tests are failing specifically, and how are they failing? Do you have the logs?

2024-05-27 12:49 UTC, plemarquand commented
@adam-fowler I've updated the CONTRIBUTING.md with instructions on importing the profile before running the tests.

2024-05-27 13:29 UTC, adam-fowler approved these changes
I think we're good

2024-05-27 16:48 UTC, merged